// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljpkpmahnbvlfhbqrzhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqcGtwbWFobmJ2bGZoYnFyemhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MzUwODQsImV4cCI6MjA1NTUxMTA4NH0.8psUFJnnWqbzpom0fzMsg6cqrAYcfCSCfCrorPZRmTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);